teleport-timer-message: "&eTeleporting to the horse race in &b%timer% &eseconds"
waiting-timer-message: "&eThe race will start in &b%timer% &eseconds... First player to complete &b3 &elaps wins!"
race-start: "&eOn your mark... get set... &bGOOOOOOOO!"
invalid-permissions: "&cYou do not have permission to execute this command!"
already-started: "&cThe horse race has already started!"
game-start: "&eStarted countdown to teleport to the horse race!"
invalid-track-location: "&cYou must first set the tracks spawn and portal locations using &e/settrack &cand &e/setportal"
set-track-location: "&eThe track's spawn location has been set to &byour current location&e!"
set-portal-location: "&eThe track's portal location has been set to &byour current location&e!"
first-player-finish: "&b%player% &ehas finished the race! You now have %b1 minute %eto finish!"
race-lap-message:
  - "&e------------=&cHorse Race&e=------------"
  - "&e                                        "
  - "&e             Current Lap: &b%current%   "
  - "&e             Needed Laps: &b3           "
  - "&e                                        "
  - "&e------------=&cHorse Race&e=------------"